"use client";

import { useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import { toast } from "sonner";
import { useDailyClosing, useSettings } from "@/lib/queries";
import { useUI } from "@/lib/store";
import {
  generatePDF,
  generatePNG,
  downloadBlob,
  printBlob,
  openWhatsAppWithReceipt,
  safeFilename,
} from "@/lib/receipt";
import type { DailyClosingReport, View } from "@/lib/types";
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import {
  MoonStar,
  Bot,
  Sparkles,
  Loader2,
  AlertTriangle,
  Brain,
  IndianRupee,
  TrendingUp,
  Receipt,
  Package,
  Banknote,
  QrCode,
  CreditCard,
  Trophy,
  Flame,
  Printer,
  MessageCircle,
  RefreshCw,
  LayoutDashboard,
  ArrowLeft,
  CheckCircle2,
  Users,
  Clock,
  Download,
} from "lucide-react";

// ---------------- helpers ----------------
function formatINR(n: number) {
  return "₹" + (n || 0).toLocaleString("en-IN");
}

function formatDate(d: string) {
  try {
    return new Date(d).toLocaleDateString("en-IN", {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  } catch {
    return d;
  }
}

function formatDateTime(d: string) {
  try {
    return new Date(d).toLocaleString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return d;
  }
}

function buildShareMessage(report: DailyClosingReport, shopName: string) {
  const s = report.summary;
  const lines: string[] = [
    `🛵 *${shopName}* — Daily Closing Report`,
    `📅 ${formatDate(report.date)}`,
    ``,
    `💰 *Revenue:* ${formatINR(s.totalRevenue)}`,
    `📈 *Profit:* ${formatINR(s.totalProfit)}`,
    `🧾 *Bills:* ${s.salesCount} | *Items:* ${s.itemsSold}`,
    ``,
    `*Payment Breakdown:*`,
    `💵 Cash: ${formatINR(s.cashTotal)}`,
    `📱 UPI: ${formatINR(s.upiTotal)}`,
    `📒 Credit: ${formatINR(s.creditTotal)}`,
  ];
  if (s.newCustomers > 0) {
    lines.push(`👤 New Customers: ${s.newCustomers}`);
  }
  if (report.topSelling.length > 0) {
    lines.push(``, `*Top Sellers:*`);
    report.topSelling.slice(0, 3).forEach((t, i) => {
      const brandStr = t.brand ? ` (${t.brand})` : "";
      lines.push(
        `${i + 1}. ${t.name}${brandStr} — ${t.qty} pcs, ${formatINR(t.revenue)}`
      );
    });
  }
  lines.push(``, `_AI-generated by ShopMitra OS_`);
  return lines.join("\n");
}

// ---------------- main component ----------------
export function CloseShopView() {
  const { go } = useUI();
  const closing = useDailyClosing();
  const { data: settingsData } = useSettings();

  const settings = settingsData?.settings;
  const shopName = settings?.shopName || "Bike Parts Shop";
  const ownerPhone = settings?.phone || "";

  const report = closing.data?.report;

  // Ref to the full report container — what the Receipt Engine captures to PDF / PNG.
  const reportRef = useRef<HTMLDivElement>(null);

  // Independent loading flags for each action button.
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const [printing, setPrinting] = useState(false);
  const [sharingWhatsApp, setSharingWhatsApp] = useState(false);

  const handleGenerate = () => {
    closing.mutate();
  };

  // ---- PDF Download (A4) — uses the Receipt Engine instead of window.print() ----
  const handleDownloadPDF = async () => {
    if (!report || !reportRef.current) return;
    setDownloadingPdf(true);
    try {
      const { blob } = await generatePDF(reportRef.current, "A4");
      downloadBlob(
        blob,
        `daily-closing-${safeFilename(report.date)}.pdf`
      );
      toast.success("PDF download ho raha hai");
    } catch (e) {
      console.error(e);
      toast.error("PDF ban nahi paayi. Dobara try karein.");
    } finally {
      setDownloadingPdf(false);
    }
  };

  // ---- Print PDF — opens the generated PDF in a hidden iframe + native OS print dialog ----
  const handlePrintPDF = async () => {
    if (!report || !reportRef.current) return;
    setPrinting(true);
    try {
      const { blob } = await generatePDF(reportRef.current, "A4");
      toast.info("Print dialog khul raha hai...");
      await printBlob(blob);
    } catch (e) {
      console.error(e);
      toast.error("Print nahi ho paaya. Dobara try karein.");
    } finally {
      setPrinting(false);
    }
  };

  // ---- WhatsApp Share — generate PNG of the report + open wa.me with prefilled text ----
  const handleShare = async () => {
    if (!report || !reportRef.current) return;
    setSharingWhatsApp(true);
    try {
      const msg = buildShareMessage(report, shopName);
      const { blob } = await generatePNG(reportRef.current, "A4");
      const filename = `daily-closing-${safeFilename(report.date)}.png`;
      const result = openWhatsAppWithReceipt(
        ownerPhone,
        msg,
        blob,
        filename
      );
      if (result.openedChat) {
        toast.success(
          "Report image download ho raha hai. WhatsApp me attach karke Send karein"
        );
      } else {
        toast.success("Report image download ho raha hai", {
          description: "WhatsApp pe manually attach karein.",
        });
      }
    } catch (e) {
      console.error(e);
      toast.error("Image ban nahi paayi. Dobara try karein.");
    } finally {
      setSharingWhatsApp(false);
    }
  };

  const handleNewReport = () => {
    closing.mutate();
  };

  // -------- Loading state --------
  if (closing.isPending) {
    return (
      <div className="space-y-5">
        <Header go={go} />
        <LoadingState />
      </div>
    );
  }

  // -------- Error state --------
  if (closing.isError && !report) {
    return (
      <div className="space-y-5">
        <Header go={go} />
        <ErrorState
          message={closing.error?.message}
          onRetry={handleGenerate}
        />
      </div>
    );
  }

  // -------- Report display --------
  if (report) {
    return (
      <div className="space-y-5">
        <Header go={go} report={report} />

        {/* ============================================================
            REPORT CAPTURE AREA
            This entire div is what the Receipt Engine renders to PDF / PNG.
            White background ensures clean print output on any printer.
           ============================================================ */}
        <div
          ref={reportRef}
          className="space-y-5"
          style={{ background: "#ffffff" }}
        >
          {/* Date banner */}
          <Card className="shadow-soft overflow-hidden py-0">
            <CardContent className="p-0">
              <div className="relative bg-gradient-to-br from-primary via-primary to-primary/85 p-5 text-primary-foreground">
                <div className="pointer-events-none absolute -right-4 -top-4 opacity-15">
                  <MoonStar className="size-28" />
                </div>
                <div className="relative flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="text-[11px] font-medium uppercase tracking-wider opacity-80">
                      Aaj ki Report
                    </p>
                    <p className="mt-0.5 text-lg font-bold leading-tight md:text-xl">
                      {formatDate(report.date)}
                    </p>
                    <p className="mt-1 flex items-center gap-1.5 text-[11px] opacity-85">
                      <Clock className="size-3" /> Generated at{" "}
                      {formatDateTime(report.generatedAt)}
                    </p>
                  </div>
                  <span className="inline-flex items-center gap-1.5 rounded-full bg-white/20 px-3 py-1 text-[11px] font-semibold backdrop-blur">
                    <CheckCircle2 className="size-3.5" />
                    Report Ready
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Summary cards grid */}
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            <SummaryCard
              icon={IndianRupee}
              label="Total Revenue"
              value={formatINR(report.summary.totalRevenue)}
              tone="primary"
            />
            <SummaryCard
              icon={TrendingUp}
              label="Total Profit"
              value={formatINR(report.summary.totalProfit)}
              tone="emerald"
            />
            <SummaryCard
              icon={Receipt}
              label="Total Bills"
              value={String(report.summary.salesCount)}
              tone="amber"
            />
            <SummaryCard
              icon={Package}
              label="Items Sold"
              value={String(report.summary.itemsSold)}
              tone="purple"
            />
          </div>

          {/* Payment breakdown + Other stats row */}
          <div className="grid gap-4 lg:grid-cols-3">
            <Card className="shadow-soft lg:col-span-2">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-base">
                  <Banknote className="size-4 text-primary" />
                  Payment Mode Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <PaymentRow
                  icon={Banknote}
                  label="Cash"
                  amount={report.summary.cashTotal}
                  total={report.summary.totalRevenue}
                  barClass="bg-emerald-500"
                  iconWrap="bg-emerald-500/10 text-emerald-500"
                />
                <PaymentRow
                  icon={QrCode}
                  label="UPI"
                  amount={report.summary.upiTotal}
                  total={report.summary.totalRevenue}
                  barClass="bg-violet-500"
                  iconWrap="bg-violet-500/10 text-violet-500"
                />
                <PaymentRow
                  icon={CreditCard}
                  label="Credit / Udhaar"
                  amount={report.summary.creditTotal}
                  total={report.summary.totalRevenue}
                  barClass="bg-amber-500"
                  iconWrap="bg-amber-500/10 text-amber-500"
                />
              </CardContent>
            </Card>

            {/* Other stats */}
            <Card className="shadow-soft">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-base">
                  <Users className="size-4 text-primary" />
                  Aur Stats
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center justify-between rounded-xl bg-primary/5 px-3 py-2.5">
                  <div className="flex items-center gap-2">
                    <span className="flex size-8 items-center justify-center rounded-lg bg-primary/15 text-primary">
                      <Users className="size-4" />
                    </span>
                    <span className="text-sm font-medium">New Customers</span>
                  </div>
                  <span className="text-lg font-bold text-primary">
                    {report.summary.newCustomers}
                  </span>
                </div>
                <div className="flex items-center justify-between rounded-xl bg-muted/50 px-3 py-2.5">
                  <div className="flex items-center gap-2">
                    <span className="flex size-8 items-center justify-center rounded-lg bg-muted text-muted-foreground">
                      <Receipt className="size-4" />
                    </span>
                    <span className="text-sm font-medium">Sales Count</span>
                  </div>
                  <span className="text-lg font-bold">
                    {report.summary.salesCount}
                  </span>
                </div>
                <div className="flex items-center justify-between rounded-xl bg-muted/50 px-3 py-2.5">
                  <div className="flex items-center gap-2">
                    <span className="flex size-8 items-center justify-center rounded-lg bg-muted text-muted-foreground">
                      <Package className="size-4" />
                    </span>
                    <span className="text-sm font-medium">Items Sold</span>
                  </div>
                  <span className="text-lg font-bold">
                    {report.summary.itemsSold}
                  </span>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Top selling + Low stock row */}
          <div className="grid gap-4 lg:grid-cols-2">
            <TopSellingCard report={report} />
            <LowStockCard report={report} />
          </div>

          {/* AI Report card (the star feature) */}
          <Card
            className="shadow-glow border-primary/30 overflow-hidden py-0"
            id="ai-report"
          >
            <div className="bg-gradient-to-br from-primary/10 via-primary/5 to-transparent">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary">
                      <Bot className="size-5" />
                    </span>
                    <div>
                      <CardTitle className="flex items-center gap-2 text-base md:text-lg">
                        <Sparkles className="size-4 text-primary" />
                        AI ki Report
                      </CardTitle>
                      <p className="mt-0.5 text-xs text-muted-foreground">
                        AI ne aapka aaj ka data analyze karke narrative banayi
                        hai
                      </p>
                    </div>
                  </div>
                  <Badge className="border-transparent bg-primary/15 text-primary">
                    <Sparkles className="size-3" />
                    AI-Generated
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                {/* No max-height/scroll here — full AI report must render in the PDF/PNG capture */}
                <div className="rounded-xl bg-background/60 p-4">
                  <AIReportContent source={report.aiReport} />
                </div>
              </CardContent>
            </div>
          </Card>
        </div>

        {/* ============================================================
            ACTION BUTTONS — outside the capture area (not in PDF/PNG)
           ============================================================ */}
        <div className="flex flex-wrap gap-2.5 pt-1">
          <Button
            onClick={handleDownloadPDF}
            disabled={downloadingPdf}
            className="touch-target h-11 flex-1 gap-2 rounded-xl"
          >
            {downloadingPdf ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Download className="size-4" />
            )}
            PDF Download
          </Button>
          <Button
            onClick={handlePrintPDF}
            variant="outline"
            disabled={printing}
            className="touch-target h-11 flex-1 gap-2 rounded-xl"
          >
            {printing ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Printer className="size-4" />
            )}
            Print PDF
          </Button>
          <Button
            onClick={handleShare}
            variant="outline"
            disabled={sharingWhatsApp}
            className="touch-target h-11 flex-1 gap-2 rounded-xl"
          >
            {sharingWhatsApp ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <MessageCircle className="size-4 text-emerald-500" />
            )}
            WhatsApp
          </Button>
          <Button
            onClick={handleNewReport}
            variant="outline"
            disabled={closing.isPending}
            className="touch-target h-11 flex-1 gap-2 rounded-xl"
          >
            <RefreshCw
              className={cn("size-4", closing.isPending && "animate-spin")}
            />
            New Report
          </Button>
          <Button
            onClick={() => go("dashboard")}
            className="touch-target h-11 flex-1 gap-2 rounded-xl"
          >
            <LayoutDashboard className="size-4" />
            Dashboard
          </Button>
        </div>
      </div>
    );
  }

  // -------- Initial state --------
  return (
    <div className="space-y-5">
      <Header go={go} />
      <InitialState onGenerate={handleGenerate} loading={closing.isPending} />
    </div>
  );
}

// ---------------- Header ----------------
function Header({
  go,
  report,
}: {
  go: (v: View) => void;
  report?: DailyClosingReport;
}) {
  return (
    <div className="flex items-start gap-3">
      <Button
        variant="ghost"
        size="icon"
        onClick={() => go("dashboard")}
        className="touch-target -ml-2 size-10 shrink-0 rounded-xl"
        aria-label="Back to Dashboard"
      >
        <ArrowLeft className="size-5" />
      </Button>
      <div className="flex items-start gap-3">
        <span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-glow">
          <MoonStar className="size-6" />
        </span>
        <div>
          <h1 className="text-xl font-bold tracking-tight md:text-2xl">
            Dukaan Band Karein
          </h1>
          <p className="text-sm text-muted-foreground">
            AI aapki aaj ki poori report banayega
          </p>
          {report && (
            <p className="mt-1 text-[11px] text-muted-foreground">
              Last generated: {formatDateTime(report.generatedAt)}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------- Initial state ----------------
function InitialState({
  onGenerate,
  loading,
}: {
  onGenerate: () => void;
  loading: boolean;
}) {
  return (
    <Card className="shadow-glow border-primary/30 overflow-hidden py-0">
      <div className="bg-gradient-to-br from-primary/10 via-primary/5 to-transparent">
        <CardContent className="flex flex-col items-center justify-center gap-5 p-8 text-center md:p-12">
          <div className="relative">
            <span className="flex size-20 items-center justify-center rounded-3xl bg-primary/15 text-primary">
              <Bot className="size-10" />
            </span>
            <span className="absolute -right-1 -top-1 flex size-7 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-soft">
              <Sparkles className="size-4" />
            </span>
          </div>

          <div className="space-y-1.5">
            <h2 className="text-lg font-bold md:text-xl">
              Aaj ki bikri kaisi rahi? AI bata dega!
            </h2>
            <p className="mx-auto max-w-md text-sm text-muted-foreground">
              Ek click karein, AI aapki aaj ki sales, profit, payment modes,
              top sellers aur low stock — sab analyze karke ek comprehensive
              report banayega.
            </p>
          </div>

          <Button
            onClick={onGenerate}
            disabled={loading}
            size="lg"
            className="touch-target h-14 gap-3 rounded-2xl px-8 text-base shadow-glow"
          >
            {loading ? (
              <>
                <Loader2 className="size-5 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="size-5" />
                Generate Closing Report
              </>
            )}
          </Button>

          <p className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <Clock className="size-3" />
            Ye 5-10 second lagayega — AI aapka data analyze kar raha hai
          </p>

          <div className="grid w-full max-w-md grid-cols-3 gap-2 pt-2">
            <FeaturePill icon={Receipt} label="Sales" />
            <FeaturePill icon={TrendingUp} label="Profit" />
            <FeaturePill icon={Package} label="Stock" />
          </div>
        </CardContent>
      </div>
    </Card>
  );
}

function FeaturePill({
  icon: Icon,
  label,
}: {
  icon: typeof Receipt;
  label: string;
}) {
  return (
    <div className="flex flex-col items-center gap-1 rounded-xl border border-border/60 bg-background/60 px-2 py-3">
      <Icon className="size-4 text-primary" />
      <span className="text-[11px] font-medium text-muted-foreground">
        {label}
      </span>
    </div>
  );
}

// ---------------- Loading state ----------------
function LoadingState() {
  return (
    <>
      <Card className="shadow-glow border-primary/30 overflow-hidden py-0">
        <CardContent className="bg-gradient-to-br from-primary/10 via-primary/5 to-transparent p-8 md:p-12">
          <div className="flex flex-col items-center justify-center gap-4 text-center">
            <div className="relative">
              <Brain className="size-16 animate-pulse text-primary" />
              <Loader2 className="absolute -bottom-1 -right-1 size-6 animate-spin rounded-full bg-background p-1 text-primary" />
            </div>
            <div className="space-y-1">
              <p className="text-base font-bold md:text-lg">
                AI aapki aaj ki report bana raha hai...
              </p>
              <p className="mx-auto max-w-md text-xs text-muted-foreground md:text-sm">
                Sales analyze ho rahi hai, profit calculate ho raha hai, kal ke
                liye suggestions ban rahe hain...
              </p>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="size-2 animate-bounce rounded-full bg-primary [animation-delay:-0.3s]" />
              <span className="size-2 animate-bounce rounded-full bg-primary [animation-delay:-0.15s]" />
              <span className="size-2 animate-bounce rounded-full bg-primary" />
            </div>
            <div className="mt-2 h-1.5 w-56 overflow-hidden rounded-full bg-muted">
              <div className="h-full w-1/2 animate-pulse rounded-full bg-primary" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Shimmer skeleton cards */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-28 rounded-2xl" />
        ))}
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Skeleton className="h-64 rounded-2xl" />
        <Skeleton className="h-64 rounded-2xl" />
      </div>
      <Skeleton className="h-72 rounded-2xl" />
    </>
  );
}

// ---------------- Error state ----------------
function ErrorState({
  message,
  onRetry,
}: {
  message?: string;
  onRetry: () => void;
}) {
  return (
    <Card className="shadow-soft">
      <CardContent className="flex flex-col items-center justify-center gap-3 p-10 text-center">
        <span className="flex size-14 items-center justify-center rounded-2xl bg-red-500/10 text-red-500">
          <AlertTriangle className="size-7" />
        </span>
        <div>
          <p className="font-bold">Report generate nahi ho paayi</p>
          <p className="mx-auto mt-1 max-w-sm text-sm text-muted-foreground">
            {message ||
              "Network ya server issue ho sakta hai. Thodi der baad dobara try karein."}
          </p>
        </div>
        <Button onClick={onRetry} size="lg" className="mt-2">
          <RefreshCw className="size-4" /> Dobara Try Karein
        </Button>
      </CardContent>
    </Card>
  );
}

// ---------------- Summary card ----------------
function SummaryCard({
  icon: Icon,
  label,
  value,
  tone,
}: {
  icon: typeof IndianRupee;
  label: string;
  value: string;
  tone: "primary" | "emerald" | "amber" | "purple";
}) {
  const toneMap = {
    primary: { wrap: "bg-primary/10 text-primary", value: "text-primary" },
    emerald: {
      wrap: "bg-emerald-500/10 text-emerald-500",
      value: "text-emerald-600 dark:text-emerald-400",
    },
    amber: {
      wrap: "bg-amber-500/10 text-amber-500",
      value: "text-amber-600 dark:text-amber-400",
    },
    purple: {
      wrap: "bg-violet-500/10 text-violet-500",
      value: "text-violet-600 dark:text-violet-400",
    },
  }[tone];
  return (
    <Card className="shadow-soft py-0">
      <CardContent className="p-4">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "flex size-8 items-center justify-center rounded-lg",
              toneMap.wrap
            )}
          >
            <Icon className="size-4" />
          </span>
          <span className="text-[11px] font-medium text-muted-foreground">
            {label}
          </span>
        </div>
        <p className={cn("mt-3 text-xl font-bold md:text-2xl", toneMap.value)}>
          {value}
        </p>
      </CardContent>
    </Card>
  );
}

// ---------------- Payment row with bar ----------------
function PaymentRow({
  icon: Icon,
  label,
  amount,
  total,
  barClass,
  iconWrap,
}: {
  icon: typeof Banknote;
  label: string;
  amount: number;
  total: number;
  barClass: string;
  iconWrap: string;
}) {
  const pct = total > 0 ? (amount / total) * 100 : 0;
  const widthPct = amount > 0 ? Math.max(pct, 4) : 0;
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "flex size-8 items-center justify-center rounded-lg",
              iconWrap
            )}
          >
            <Icon className="size-4" />
          </span>
          <span className="text-sm font-medium">{label}</span>
        </div>
        <div className="text-right">
          <span className="text-sm font-bold">{formatINR(amount)}</span>
          <span className="ml-1.5 text-[11px] text-muted-foreground">
            {pct.toFixed(1)}%
          </span>
        </div>
      </div>
      <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
        <div
          className={cn(
            "h-full rounded-full transition-all duration-500",
            barClass
          )}
          style={{ width: `${widthPct}%` }}
        />
      </div>
    </div>
  );
}

// ---------------- Top selling card ----------------
function TopSellingCard({ report }: { report: DailyClosingReport }) {
  const items = report.topSelling;
  return (
    <Card className="shadow-soft">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Trophy className="size-4 text-amber-500" />
          Aaj ke Top Sellers
        </CardTitle>
      </CardHeader>
      <CardContent>
        {items.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
            <span className="flex size-12 items-center justify-center rounded-2xl bg-muted text-muted-foreground">
              <Receipt className="size-6" />
            </span>
            <p className="text-sm font-medium">Aaj koi sale nahi hui</p>
            <p className="text-xs text-muted-foreground">
              Kal ki sales yahan dikhegi
            </p>
          </div>
        ) : (
          <ul className="space-y-2.5">
            {items.map((it, i) => {
              const isTop3 = i < 3;
              return (
                <li
                  key={it.name + "_" + i}
                  className="flex items-center gap-3 rounded-xl border border-border/50 bg-card/50 px-3 py-2.5"
                >
                  <span
                    className={cn(
                      "flex size-8 shrink-0 items-center justify-center rounded-lg text-xs font-bold",
                      isTop3
                        ? "bg-amber-500/15 text-amber-500"
                        : "bg-muted text-muted-foreground"
                    )}
                  >
                    {isTop3 ? (
                      <Trophy className="size-4" />
                    ) : (
                      i + 1
                    )}
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-semibold leading-tight">
                      {it.name}
                    </p>
                    <p className="truncate text-[11px] text-muted-foreground">
                      {it.brand || "No brand"} · {it.qty} pcs sold
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-bold text-emerald-600 dark:text-emerald-400">
                      {formatINR(it.revenue)}
                    </p>
                    {isTop3 && (
                      <Flame className="ml-auto size-3 text-amber-500" />
                    )}
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

// ---------------- Low stock card ----------------
function LowStockCard({ report }: { report: DailyClosingReport }) {
  const items = report.lowStock;
  return (
    <Card className="shadow-soft">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <AlertTriangle className="size-4 text-amber-500" />
          Restock Zaroorat
        </CardTitle>
      </CardHeader>
      <CardContent>
        {items.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
            <span className="flex size-12 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-500">
              <CheckCircle2 className="size-6" />
            </span>
            <p className="text-sm font-medium">Sab stock healthy hai</p>
            <p className="text-xs text-muted-foreground">
              Koi urgent restock zaroorat nahi
            </p>
          </div>
        ) : (
          <ul className="max-h-80 space-y-2 overflow-y-auto scroll-thin pr-1">
            {items.map((it, i) => {
              const isOut = it.quantity <= 0;
              const isLow = !isOut && it.quantity <= it.minStock;
              return (
                <li
                  key={it.name + "_" + i}
                  className={cn(
                    "flex items-center gap-3 rounded-xl border px-3 py-2.5",
                    isOut
                      ? "border-red-500/30 bg-red-500/5"
                      : isLow
                        ? "border-amber-500/30 bg-amber-500/5"
                        : "border-border/50 bg-card/50"
                  )}
                >
                  <span
                    className={cn(
                      "flex size-8 shrink-0 items-center justify-center rounded-lg",
                      isOut
                        ? "bg-red-500/15 text-red-500"
                        : "bg-amber-500/15 text-amber-500"
                    )}
                  >
                    <AlertTriangle className="size-4" />
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-semibold leading-tight">
                      {it.name}
                    </p>
                    <p className="truncate text-[11px] text-muted-foreground">
                      {it.brand || "No brand"}
                    </p>
                  </div>
                  <div className="text-right">
                    <p
                      className={cn(
                        "text-sm font-bold",
                        isOut
                          ? "text-red-500"
                          : "text-amber-600 dark:text-amber-400"
                      )}
                    >
                      {it.quantity} / {it.minStock}
                    </p>
                    <p className="text-[10px] text-muted-foreground">
                      {isOut ? "Out of stock" : "min stock"}
                    </p>
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

// ---------------- AI Report content (markdown) ----------------
function AIReportContent({ source }: { source: string }) {
  return (
    <div className="text-sm leading-relaxed text-foreground">
      <ReactMarkdown
        components={{
          h1: ({ node, ...props }) => (
            <h1
              className="mb-2 mt-2 text-lg font-bold text-primary first:mt-0"
              {...props}
            />
          ),
          h2: ({ node, ...props }) => (
            <h2
              className="mb-1.5 mt-3 text-base font-bold text-primary first:mt-0"
              {...props}
            />
          ),
          h3: ({ node, ...props }) => (
            <h3 className="mb-1 mt-2 text-sm font-bold" {...props} />
          ),
          p: ({ node, ...props }) => (
            <p className="mb-2 text-sm leading-relaxed" {...props} />
          ),
          ul: ({ node, ...props }) => (
            <ul
              className="mb-2 list-disc space-y-1 pl-5 text-sm"
              {...props}
            />
          ),
          ol: ({ node, ...props }) => (
            <ol
              className="mb-2 list-decimal space-y-1 pl-5 text-sm"
              {...props}
            />
          ),
          li: ({ node, ...props }) => (
            <li className="text-sm" {...props} />
          ),
          strong: ({ node, ...props }) => (
            <strong className="font-bold text-foreground" {...props} />
          ),
          em: ({ node, ...props }) => (
            <em className="italic text-muted-foreground" {...props} />
          ),
          hr: ({ node, ...props }) => (
            <hr className="my-3 border-border" {...props} />
          ),
          blockquote: ({ node, ...props }) => (
            <blockquote
              className="my-2 border-l-2 border-primary bg-muted/40 py-2 pl-3 text-sm italic text-muted-foreground"
              {...props}
            />
          ),
          code: ({ node, className, children, ...props }) => {
            const isInline = !className;
            if (isInline) {
              return (
                <code
                  className="rounded bg-muted px-1.5 py-0.5 font-mono text-[12px] text-primary"
                  {...props}
                >
                  {children}
                </code>
              );
            }
            return (
              <pre className="my-3 overflow-x-auto rounded-xl bg-muted p-3 text-xs">
                <code className="font-mono" {...props}>
                  {children}
                </code>
              </pre>
            );
          },
          a: ({ node, href, children, ...props }) => (
            <a
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline underline-offset-2"
              {...props}
            >
              {children}
            </a>
          ),
        }}
      >
        {source}
      </ReactMarkdown>
    </div>
  );
}
